
spring:
  datasource:
    password: cloudoper123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rds.cqximo.com:3306/cloudoper?useUnicode=true&characterEncoding=UTF-8
    username: cloudoper
    druid:
      max-pool-prepared-statement-per-connection-size: 5
      min-idle: 2
      validation-query-timeout: 1
      max-active: 30
      test-while-idle: true
      time-between-eviction-runs-millis: 10000
      validation-query: select 1
      aop-patterns: com.madlyai.repository.*
      max-wait: 1234
      test-on-borrow: true
      pool-prepared-statements: true
      initial-size: 2
      min-evictable-idle-time-millis: 30001
      async-close-connection-enable: true
      test-on-return: true
      primary:
        password: cloudoper123456
        max-active: 10
        max-wait: 10000
        url: jdbc:mysql://rds.cqximo.com:3306/cloudoper?useUnicode=true&characterEncoding=UTF-8
        username: cloudoper
      secondary:
        password: emvc123456
        max-active: 20
        max-wait: 20000
        url: jdbc:mysql://rds.cqximo.com:3306/emvc?useUnicode=true&characterEncoding=UTF-8
        username: emvc
      filter:
        stat:
          db-type: mysql
          slow-sql-millis: 2000
          log-slow-sql: true
  jpa:
    showSql: true
    generateDdl: true
    hibernate:
      show-sql: false
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format-sql: true
      ddlAuto: none
      naming:
        implicitStrategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physicalStrategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy