
spring:
  datasource:
    username: cloudoper
    password: cloudoper123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rds.cqximo.com:3306/cloudoper?useUnicode=true&characterEncoding=UTF-8
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 30
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query-timeout: 1
      max-pool-prepared-statement-per-connection-size: 20
      test-while-idle: true
      validation-query: select 1
      aop-patterns: com.madlyai.repository.*
      test-on-borrow: true
      pool-prepared-statements: true
      async-close-connection-enable: true
      test-on-return: true
      primary:
        password: cloudoper123456
        max-active: 10
        max-wait: 10000
        url: jdbc:mysql://rds.cqximo.com:3306/cloudoper?useUnicode=true&characterEncoding=UTF-8
        username: cloudoper
      secondary:
        password: emvc123456
        max-active: 20
        max-wait: 20000
        url: jdbc:mysql://rds.cqximo.com:3306/emvc?useUnicode=true&characterEncoding=UTF-8
        username: emvc
      filter:
        stat:
          db-type: mysql
          slow-sql-millis: 2000
          log-slow-sql: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: none
    hibernate:
      naming:
        implicitStrategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physicalStrategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy